#### 创建一个DataFrame

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"a":[1,2,3],"b":[4,5,6],"c":[7,8,9]})

In [3]:
df

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [4]:
df["b"].at[1]  # df["b"] 是一个Series，此时at函数只需取行名即可

5

In [5]:
df.at[1,"b"]  # at函数通过行名和列名来取值

5

In [6]:
df.iat[1,1]  # iat函数通过行号和列号来取值，行号和列号从0开始。

5

In [7]:
f = pd.DataFrame({"name":["aoe","bob","cool"],"value":[3,4,5],"nature":["a","b","c"]})

In [8]:
f.set_index("name",inplace = True,drop = False)

In [9]:
f

      name  value nature
name
aoe    aoe      3      a
bob    bob      4      b
cool  cool      5      c

In [10]:
f.at["bob","nature"]

'b'

In [11]:
f["value"].at["cool"]

5

In [12]:
f["test"]=None

In [13]:
for i in f.index:
    f["test"].at[i] = f["value"].at[i]+1

In [14]:
f

      name  value nature test
name
aoe    aoe      3      a    4
bob    bob      4      b    5
cool  cool      5      c    6

In [15]:
f["test1"]=f["value"]+1

In [16]:
f

      name  value nature test  test1
name
aoe    aoe      3      a    4      4
bob    bob      4      b    5      5
cool  cool      5      c    6      6

In [17]:
s = pd.Series([4,5,6])

In [18]:
s

0    4
1    5
2    6
dtype: int64

In [19]:
s.dtype

dtype('int64')

In [21]:
def getsum(x):
    return x["a"]+x["b"]+x["c"]

In [22]:
df["d"]=df.apply(getsum,axis=1)

In [23]:
df

   a  b  c   d
0  1  4  7  12
1  2  5  8  15
2  3  6  9  18

In [24]:
df["e"]=df.apply(lambda x:x["a"]+x["b"],axis=1) # 相当于df["e"]=df["a"]+df["b"],但apply能实现更复杂的计算

In [25]:
df

   a  b  c   d  e
0  1  4  7  12  5
1  2  5  8  15  7
2  3  6  9  18  9